### PR TITLE
Implement new Dataset details page top layout

### LINKED ISSUE #340: Dataset details page: New page layout
Modify general layout of dataset details pages following screenshots below.

The main objective is to clearly separate information on `What dataset is expected` from information on the actual `Submission`, what is evaluated.

The secondary objective is to provide more explanation on the open data evaluation of the dataset.
This is further explained in issue #343

The third objective is to enable users to see alternative datasets at global or country level (submissions for same dataset and same country or for same dataset and world that may be used as an alternative of this dataset). This is further explained in #341

Page by default (not expanded) 

image

Page with open data criteria visible

image

### PR DESCRIPTION
**Pull request by oncletom**
refs #340

### CODE REVIEW

**Comment by oncletom** [comment]
Early work enables the [**Deploy Preview**](https://deploy-preview-346--index-opendri-preview.netlify.com/) feature I have been longing for.

**Comment by oncletom** [comment]
Current status.

screenshot 2018-12-04 at 16 53 52

**Comment by pzwsk** [comment]
Thanks @oncletom 

here what I see on preview, small issue on Useful for

image

Question: what do you use to retrieve list of hazard for Useful for? 
I should have mentioned but API return an `applicable for` field, this is the one to use.

**Comment by oncletom** [comment]
@pzwsk thanks, it was due to un unclosed tag 😅 

I'm going to fix the field source tomorrow, thanks for the heads up.

**Comment by pzwsk** [comment]
Hi @oncletom dev.riskopendata.org is broken, it seems an issue with css files but I am not sure.

**Comment by oncletom** [comment]
@pzwsk correct! I fixed it with 492082b.

Previously, dependencies were checked out with Git whereas now, they are pulled remotely, and they were cleaned out by the CI system. It should be fine now 🙂

**Pull request merged**
