### PR TITLE
Preload fonts, prioritize stylesheets and delay scripts to speed up page load

### PR DESCRIPTION
**Pull request by oncletom**
Some stuff taken by watching this video: https://youtu.be/cznVISavm-k?t=210

### CODE REVIEW

**Comment by CIMAManuel** [comment]
Good to know.
I saw a piece of video, very interesting, thks.
I'll watch it all later.

**Comment by oncletom** [comment]
image

**Comment by newick** [comment]
To help choosing a font stack, [a great website](https://www.cssfontstack.com/) which displays what font can be find on what OS (maybe not up to date but it gives an idea)

**Comment by newick** [comment]
To help choosing a font stack, [a great website](https://www.cssfontstack.com/) which displays what font can be find on what OS (maybe not up to date but it gives an idea)

**Comment by oncletom** [comment]
Change is too big. Will create smaller pull requests.

**Pull request closed without merging**
