### PR TITLE
Dataset page title: active seismic fault (dataset) should be more prominent than Serbia (country). For example, country can be smaller and lighter font, with dataset below it larger

### PR DESCRIPTION
**Pull request by oncletom**
Using Bootstrap Page Header component: https://getbootstrap.com/docs/3.3/components/#page-header

Submitted by @gracedoherty.

### CODE REVIEW

**Comment by oncletom** [comment]
This is the current take at this issue.

image

**Comment by oncletom** [comment]
It looks like this on mobile devices.

capture d ecran - 2018-10-10 a 10 27 36

**Comment by pzwsk** [comment]
Thanks,

I agree with proposal but feel this be should be addressed as part of aligning layout of pages with other Lab products. What do you think?

Here is a quick shot of what it could look like:

image

Can spend more time latter today on this.

**Comment by oncletom** [comment]
I'm fine doing that. I understand it as: 

- moving out of the _all caps_ writing
- move the subtitle under the title
- matching the font sizes for both title and subtitle

**Comment by oncletom** [comment]
@dedandy the pull request was still being reviewed 😢 the merge happened a bit too soon. Please move cards you work or merge pull requests that you proposed, but not for others.

**Pull request merged**
