### PR TITLE
BE: new scoring per country

### PR DESCRIPTION
**Pull request by nastasi-oq**
The new scoring per country is available at: [exp.riskopendata.org//api/scoring/AL](https://exp.riskopendata.org/api/scoring/AL)
@oncletom: attribute like perils counters are still needed ? Please let me know what are missing in this view.
Possible categories are: ``open``, ``restricted``, ``closed``, ``unknown``.
The new scoring per country output is:
```json
{
    "keydatasets_count": 25,
    "scores": [
        {
            "is_open_licence": true,
            "is_digital_form": true,
            "name": "Flood hazard maps",
            "keydataset_id": "HA_6A",
            "title": null,
            "is_bulk_avail": false,
            "is_avail_online_meta": true,
            "is_pub_available": true,
            "institution": "",
            "is_avail_for_free": false,
            "is_machine_read": true,
            "is_prov_timely_last": "",
            "score": 0,
            "modify_time": "",
            "is_avail_online": false,
            "is_existing_txt": "",
            "is_prov_timely": false,
            "is_existing": true,
            "dataset_id": 529,
            "category": "restricted"
        },
        ....
    ],
    "fullscores_count": 2,
    "datasets_count": 37
}
```

### CODE REVIEW

**Comment by oncletom** [comment]
#432 is already based on this PR, you can preview the output here: https://deploy-preview-432--index-opendri-preview.netlify.com/dataset_list.html?idcountry=MW

**Question**: The new API returns data only for existing datasets, is there a way to fetch all KeyDatasets in 1 request so as I can list them as "missing datasets"?

image

**Comment by nastasi-oq** [comment]
@oncletom about missing dataset let me check.

About new primary fields are you waiting for total number of datasets for each category (``datasets_{open,restricted,closed,unknown}_count``), right ?

**Comment by oncletom** [comment]
Well, I'm good with the "counts" (I compute them client-side) but if you provide the counts, I will use them instead. It's up to you.

**Comment by nastasi-oq** [comment]
@oncletom

- missing datasets included (with 'dataset_id': null)
- ``*_count`` attributes added
- ``category`` == "``opendata``" instead of "``open``" to be FE compliant.

Already on ``exp.``.

```json
{
    "datasets_closed_count": 4,
    "datasets_count": 37,
    "datasets_restricted_count": 31,
    "datasets_unknown_count": 11,
    "scores": [
        {
            "keydataset_id": "HA_6A",
            "is_open_licence": true,
            "title": null,
            "institution": "",
            "is_avail_online": false,
            "is_machine_read": true,
            "is_existing_txt": "",
            "is_existing": true,
            "modify_time": "",
            "dataset_id": 529,
            "is_bulk_avail": false,
            "name": "Flood hazard maps",
            "category": "restricted",
            "is_digital_form": true,
            "is_avail_for_free": false,
            "is_pub_available": true,
            "is_avail_online_meta": true,
            "score": 0,
            "is_prov_timely_last": "",
            "is_prov_timely": false
        },
....
// for missing keydatasets "dataset_id": null, like:
{ 
            "keydataset_id": "HA_10",
            "is_open_licence": false,
            "title": null,
            "institution": null,
            "is_avail_online": false,
            "is_machine_read": false,
            "is_existing_txt": false,
            "is_existing": false,
            "modify_time": null,
            "dataset_id": null,
            "is_bulk_avail": false,
            "name": "Nearshore tsunami wave height",
            "category": "unknown",
            "is_digital_form": false,
            "is_avail_for_free": false,
            "is_pub_available": false,
            "is_avail_online_meta": false,
            "score": -1,
            "is_prov_timely_last": false,
            "is_prov_timely": false
        },
    ],
    "datasets_open_count": 2,
    "keydatasets_count": 25
}
```

**Comment by pzwsk** [comment]
Looks good, 

Question: is the score still useful? going to be removed?

**Comment by oncletom** [comment]
We don't use the `score` field so it can safely be removed.

**Comment by pzwsk** [comment]
@nastasi-oq can you remove `score` and then merge?

**Pull request merged**
