### PR TITLE
Replace home indicators with new ones

### LINKED ISSUE #431: Home page: use new indicators for datasets, open data and countries
Needs to make it indicators consistent between each other:

Currently, users can read the indicators this way:
`X datasets, including Y % open data, covering Y countries`

### PR DESCRIPTION
**Pull request by oncletom**
image

@nastasi-oq the `api/stats` is no longer in use.

fix #431

### CODE REVIEW

**Comment by pzwsk** [comment]
Thanks, let me do some tests from this version before merging.

**Comment by oncletom** [comment]
Sure 👍 here is the link to the [live preview](https://deploy-preview-458--index-opendri-preview.netlify.com/).

**Comment by oncletom** [comment]
Here is the current proposal.

image


> For the hazard icons: could you include a row of icons, with the # datasets directly below? I think would look quite tidy. Would be useful I think to include exposure and base data as an icon too.

I don't have access to this information. At best, I can list the "perils" (by adding an extra API call), but not the figures.

Otherwise I have to go through all the datasets but we hit #280 again. If the scores are removed, maybe it would speed up this API route and make it useable for this purpose on the homepage.

**Comment by gracedoherty** [comment]
It looks very nice. If we just need this quickly updated, then the only change I have is:
"185 datasets in 21 countries to date." 
(Tested "and counting" with a non-native English speaking colleague and Stu was right that it is not a familiar term).

If we have more time, another change I'd make is to remove the grey boxes behind the "Tracking..." and "Discover..." lines. It looks unfinished or like it's been highlighted by your cursor.

**Comment by stufraser1** [comment]
Perhaps the '57 could be improved' could be more specific in its wording.

E.g. '57 are partially open'. If that can be considered technically
correct/possible

'could be improved' doesn't say anything to me about improving openness,and
could be taken to mean they need to be improved in terms of data quality.

Similar comment for 'could be opened'. There may be reasons a dataset is
not open, and that may not change so the dataset is not possible to open in
the near or far future.
Consider instead 'N datasets are not open' (or 'are closed', given that
term is used above on the page)

**Comment by oncletom** [comment]
I have taken in account (all of) your feedbacks 👍 

image

**Comment by pzwsk** [comment]
LIke it thanks

**Comment by vdeparday** [comment]
Could we also have the missing ones and a call for action? Something like
still look for X datasets, help us contribute ! So that we incentivize
people to contribute ?

**Pull request merged**
