### PR TITLE
FE minor modifications

### PR DESCRIPTION
**Pull request by pzwsk**
Some minor modifications for homepage and static pages.
Please let me know if process now ok.
Best

### CODE REVIEW

**Comment by nastasi-oq** [comment]
@pzwsk: maybe add a reviewer explicitly speedup the integration.

**Comment by pzwsk** [comment]
Not sure to understand why there is a conflict. Only change for methodology.html is this one 
image

**Comment by CIMAManuel** [comment]
in these days we have changed some files, so i think the version is different (conflict).
Perhaps you must update your files.
i posted in dev version the modifications, let me know if ok

**Comment by pzwsk** [comment]
Ok please reject this PR then, and I will work from latest version.
Not sure to understand why there is a conflict though.
Best

**Comment by nastasi-oq** [comment]
@pzwsk there are modifications on the same part of code on your fork and on master from your latest fork refresh, I'm currently see this as conflict:
<<<<<<< HEAD
            <p></p>
=======
            <div></div>
>>>>>>> origin/master
Align with @CIMAManuel  about the right solution.

**Pull request closed without merging**
