### PR TITLE
Display open data value as a progressbar

### LINKED ISSUE #270: Change datasets submitted column to a data visualization that shows the number out of 36.
A simple horizontal fill bar like what is existing for the score would fit well with the existing layout. Could have it change color as it gets filled (e.g. from red to green).

### LINKED ISSUE #271: Change open data column to a data visualization that shows the number out of 36.
A simple horizontal fill bar like what is existing for the score would fit well with the existing layout. Could have it change color as it gets filled (e.g. from red to green).

### PR DESCRIPTION
**Pull request by oncletom**
image

closes #270 
closes #271

### CODE REVIEW

**Comment by pzwsk** [comment]
Hi @gracedoherty , waiting for your comment/approval to merge this one. Thanks!

**Comment by oncletom** [comment]
@pzwsk is a gradient between two colours more readable? Otherwise as a starter, we can reuse the same colour scheme as the `score` column. Or reuse the colour proposal you screened on https://github.com/GFDRR/open-risk-data-dashboard/issues/264#issuecomment-430778372

**Comment by pzwsk** [comment]
Not sure, I find gradient a bit distracting, but need to see best practices, examples, and in any case, this will be a transition between current version and next one with new indicators.

**Comment by oncletom** [comment]
Right. So let's go simple and we can improve them after browsing good practices :)

I've update the bars to look like the `Score` ones (same blue background colour).

**Pull request merged**
