### PR TITLE
Favicon fix all pages

### PR DESCRIPTION
**Pull request by dedandy**
#266 fix favicon

### CODE REVIEW

**Comment by dedandy** [comment]
Yes, I look after change... Fixed in #269 with replace main logo and favicon with newer image

**Comment by newick** [comment]
Go for it :)

**Comment by oncletom** [comment]
Hm, but what about @newick comment about the `about.html`?

**Comment by newick** [comment]
@oncletom it was corrected in another PR #269 if I understood correctly

**Comment by oncletom** [comment]
Okay perfect, I misread the comment. Thank you!

**Pull request merged**
