### PR TITLE
Improve registration mail

### PR DESCRIPTION
**Pull request by dedandy**
#182 
Improve registration mail, adding new gif logo mail & logo partner.
Simplify structure without any background img.... maybe further...

This look now:

### CODE REVIEW

**Comment by pzwsk** [comment]
Thanks but I had suggested text in #182 (this version with reference to RODI and dashboard is not relevant anymore)

So, please use this one:

**Thank you!**

You requested to register to the Open Data for Resilience Index.

Please confirm your registration by clicking on the button below.

`Confirm`

Also, please remove "an initiative of" next to GDFRR logo

**Comment by dedandy** [comment]
@pzwsk @oncletom update registration mail done with your suggests, can you review please? :)

**Comment by pzwsk** [comment]
Hi @dedandy 

you have not followed instruction for text in the comments above. Did you see them?
I made a new commit in your branch including those changes.

**Comment by pzwsk** [comment]
Also, when you merge please inform @nastasi-oq as we need to update in backend side as I understand, thanks

**Comment by dedandy** [comment]
I add  @nastasi-oq as reviewers too :)

**Pull request merged**
